version: '3.8'

services:
  checkcarsapi:
    image: checkcarsapi:development
    build:
      context: ./CheckCarsAPI/
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
      - "443:443" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

      # SMTP
      - Smtp__Host=smtp.example.com
      - Smtp__Port=587
      - Smtp__EnableSsl=true
      - Smtp__Username=example.user@example.com
      - Smtp__Password=example-password-123
      - Smtp__From=example.user@example.com
      - Smtp__DefaultEmail=example.user@example.com

      # Connection strings
      - ConnectionStrings__IdentityUsers=Data Source=sqlserver;Initial Catalog=ExampleDB_Users;User ID=sa;Password=ExamplePassword123!;TrustServerCertificate=True;
      - ConnectionStrings__ReportsConnection=Data Source=sqlserver;Initial Catalog=ExampleDB;User ID=sa;Password=ExamplePassword123!;TrustServerCertificate=True;

      # JWT
      - Jwt__Issuer=example.com
      - Jwt__Audience=example.com
      - Jwt__Key=dGVzdC1rZXktZXhhbXBsZS1qcz0tZXhhbXBsZQ==

      # Static files
      - StaticFiles__ImagesPath=images

    depends_on:
      - sqlserver
    volumes:
      - ./images:/app/images

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "ExamplePassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
