version: '3.8'

services:
  checkcars-api:
    image: checkcars-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Smtp__Host=Smtp.gmail.com
      - Smtp__Port=587
      - Smtp__EnableSsl=true
      - Smtp__Username=${SMTP_USERNAME}
      - Smtp__Password=${SMTP_PASSWORD}
      - Smtp__From=steven.gazo@grupomecsa.net
      - Smtp__DefaultEmail=steven.gazo@grupomecsa.net
      - ConnectionStrings__IdentityUsers=${DB_USERS_CONN}
      - ConnectionStrings__ReportsConnection=${DB_REPORTS_CONN}
      - Jwt__Issuer=yourdomain.com
      - Jwt__Audience=yourdomain.com
      - Jwt__Key=${JWT_KEY}
      - StaticFiles__ImagesPath=images
    depends_on:
      - sqlserver
    volumes:
      - ./images:/app/images

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "TuPasswordSegura123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
