using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CheckCarsAPI.Models
{
    /// <summary>
    /// Represents a photo associated with a report.
    /// </summary>
    public class Photo
    {
        /// <summary>
        /// Gets or sets the unique identifier for the photo.
        /// This value is not generated by the database.
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public string? PhotoId { get; set; }

        /// <summary>
        /// Gets or sets the file name of the photo (optional).
        /// </summary>
        public string? FileName { get; set; }

        /// <summary>
        /// Gets or sets the file path or URL where the photo is stored (optional).
        /// </summary>
        public string? FilePath { get; set; }

        /// <summary>
        /// Gets or sets the date when the photo was taken.
        /// </summary>
        public DateTime DateTaken { get; set; }

        /// <summary>
        /// Gets or sets the identifier of the report associated with this photo (optional).
        /// </summary>
        [ForeignKey("Report")]
        public string? ReportId { get; set; }

        /// <summary>
        /// Gets or sets the report related to this photo (optional).
        /// </summary>
        public Report? Report { get; set; }
    }
}
