// <auto-generated />
using System;
using CheckCarsAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CheckCarsAPI.Migrations.ReportsDb
{
    [DbContext(typeof(ReportsDbContext))]
    [Migration("20241113174115_appReports")]
    partial class appReports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("ReportSequence");

            modelBuilder.Entity("CheckCars.Models.Photo", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhotoId"));

                    b.Property<DateTime>("DateTaken")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.HasKey("PhotoId");

                    b.HasIndex("ReportId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("CheckCars.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [ReportSequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<int>("ReportId"));

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarPlate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.HasKey("ReportId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("CheckCars.Models.CrashReport", b =>
                {
                    b.HasBaseType("CheckCars.Models.Report");

                    b.Property<string>("CrashDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CrashedParts")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfCrash")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("CrashReports");
                });

            modelBuilder.Entity("CheckCars.Models.EntryExitReport", b =>
                {
                    b.HasBaseType("CheckCars.Models.Report");

                    b.Property<double>("FuelLevel")
                        .HasColumnType("float");

                    b.Property<bool>("HasChargerUSB")
                        .HasColumnType("bit");

                    b.Property<bool>("HasEmergencyKit")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPhoneSupport")
                        .HasColumnType("bit");

                    b.Property<bool>("HasQuickPass")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSpareTire")
                        .HasColumnType("bit");

                    b.Property<string>("InteriorsState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MecanicState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OilLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaintState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TiresState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("mileage")
                        .HasColumnType("bigint");

                    b.ToTable("EntryExitReports");
                });

            modelBuilder.Entity("CheckCars.Models.IssueReport", b =>
                {
                    b.HasBaseType("CheckCars.Models.Report");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("IssueReports");
                });

            modelBuilder.Entity("CheckCars.Models.Photo", b =>
                {
                    b.HasOne("CheckCars.Models.Report", "Report")
                        .WithMany("Photos")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("CheckCars.Models.Report", b =>
                {
                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
