version: '3.8'

services:
  checkcarsapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=TestCheckCarsUsers;User Id=sa;Password=Siera4388$;TrustServerCertificate=True;
      - ConnectionStrings__ReportsConnection=Server=sqlserver,1433;Database=TestCheckCarsReports;User Id=sa;Password=Siera4388$;TrustServerCertificate=True;
      - Jwt__Issuer=yourdomain.com
      - Jwt__Audience=yourdomain.com
      - Jwt__Key=c3VwZXJzZWN1cmVzc2ltdWx0YXBhc3N3b3JkYmFzaWNhbmdsaWZl
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
      - AllowedHosts=*
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Siera4388$"
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
