name: Build and Test API and Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.x' # Ajusta si usas otra versión

    - name: Restore dependencies
      run: dotnet restore ./CheckCarsAPI.sln

    - name: Build solution
      run: dotnet build ./CheckCarsAPI.sln --no-restore --configuration Release

    - name: Run tests
      run: dotnet test ./CheckCarsAPI.sln --no-build --configuration Release --logger trx
