name: Docker Compose CI

on:
  push:
    branches:
      - main
      - Development
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set version tag
      id: vars
      run: echo "VERSION_TAG=desarrollo-$(date +%Y%m%d)" >> $GITHUB_ENV

    - name: Build Docker image with date tag
      uses: docker/build-push-action@v5
      with:
        context: ./CheckCarsAPI
        file: ./CheckCarsAPI/Dockerfile
        push: false
        tags: checkcarsapi:${{ env.VERSION_TAG }}

    - name: Run docker-compose with version tag
      env:
        VERSION_TAG: ${{ env.VERSION_TAG }}
      run: |
        echo "Usando imagen checkcarsapi:${VERSION_TAG}"
        VERSION_TAG=${VERSION_TAG} docker compose -f docker-compose.yml up -d

